services:
  postgresdb:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=trade-app
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=trade-app-db
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "6868:8080"
    environment:
      - POSTGRESDB_HOST=postgresdb
      - POSTGRESDB_USER=trade-app
      - POSTGRESDB_ROOT_PASSWORD=123456
      - POSTGRESDB_DATABASE=trade-app-db
      - POSTGRESDB_DOCKER_PORT=5432
      - DB_HOST=postgresdb
      - DB_USER=trade-app
      - DB_PASSWORD=123456
      - DB_NAME=trade-app-db
      - DB_PORT=5432
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@trade.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgresdb

volumes:
  db: